### ISSUE TITLE
Create an ffmpeg utility, like AudioChannelManipulation, to do some media file analysing

### ISSUE THREAD

**Issue by hdsdi3g** [hdsdi3g/medialib#14]
AKA create a parser for #13 results.

Get in realtime, or in onEnd mode.

TODO:
 - [x] Create an manual command-line ffmpeg exec, and generate some datas
 - [x] See https://ffmpeg.org/ffmpeg-filters.html#metadata_002c-ametadata to better data crawl, or not.
 - [x] Precheck filters availablity before run analysing
 - [x] Create an event capture API to transform raw ffmpeg datas to real Java objects
 - [x] Implements parsers for:
   - [x] Audio
     - [x] ebur128 (live mode) - must parse ffmpeg out
     - [x] ebur128 (result mode) - must parse ffmpeg out
     - [x] aphasemeter - just read lavfi metadata file
     - [x] silencedetect - just read lavfi metadata file
     - [x] astats - just read lavfi metadata file
     - [x] ~~volumedetect~~ optional, must parse ffmpeg out
   - [x] Video
     - [x] siti - just read lavfi metadata file
     - [x] idet - just read lavfi metadata file
     - [x] freezedetect - just read lavfi metadata file
     - [x] blackdetect - just read lavfi metadata file
     - [x] cropdetect - just read lavfi metadata file
     - [x] blockdetect - just read lavfi metadata file
     - [x] blurdetect - just read lavfi metadata file
     - [x] ~~mestimate~~ only with cropdetect 
 - [x] ~~Create a test suite with automatic generated files to check it?~~
 - [x] ~~Check loudness with very long files (memory max?)~~
 - [x] Create a filterchain utility, and setup default params
 - [x] ~~Add the help of AudioChannelManipulation with the audio, with separated tracks (MXF).~~ Moved to https://github.com/hdsdi3g/medialib/issues/22
 - [x] ~~Manage splited silence check?~~
 - [x] ~~Manage limited time for idet scan?~~ moved to https://github.com/hdsdi3g/medialib/issues/23
 - [x] ~~Create a real command line tool (new project):~~ moved to https://github.com/hdsdi3g/medialib/issues/21
 - [x] create "parser" to merge LavfiMetadataFilterFrame and FilterSupplier (? or create LavfiMetadataFilterSupplier ?)
